### ISSUE TITLE
Connecting to xDefi defaults to the first account, not the active account

### ISSUE THREAD

**Issue by azza2902** [thorswap/thorswap-finance-app#263]
I'd like to be able to connect to any of my accounts in xDefi by first selecting the account I want in the chrome extension, and then connecting to xDefi in Thorswap. Currently, Thorswap defaults to the first account in xDefi

**Comment by bullishtrader** [comment]
Hi @azza2902 , currently this is possible but there should be some UI improvements from XDEFI.

**How to connect a different account to THORSwap:**

**(1)** Click on `Connections` (top right corner) 

![Schermata 2021-07-01 alle 14 03 24](https://user-images.githubusercontent.com/82927810/124122097-fcaa9a80-da75-11eb-9088-02771eb44bb7.png)

**(2)** Click `Connect` 

**(3)** Now, you have 2 accounts connected to app.thorswap.finance though, that's why i said there should be an UI improvements, XDEFI should not allow users to connect 2 accounts simultaneously.

**(4) To connect the secondary account, you should "delete" the first account, doing so you will be able to connect with the 2nd account.

**Be aware, your account WILL NOT BE deleted, but you will need to approve the connection again if you want to connect again to this account**

Click on this icon: 

![Schermata 2021-07-01 alle 14 09 12](https://user-images.githubusercontent.com/82927810/124122584-89555880-da76-11eb-9d98-5d39592d85ce.png)

Now you can connect your Secondary account, i will forward this Improvement to XDEFI Team to allow users to choose the account users want to connect, when there are 2 accounts or more.

Thanks

**Comment by azza2902** [comment]
Hi,

Thanks for the info, and I've followed this successfully. However, when I
look back in Thorswap and attempt to refresh my positions, nothing updates.
So, while xDefi says I am connected to Account 2 and not connected to
Account 1, Thorswap continues to display my Account 1 balances. To get my
balances to display correctly in Thorswap, I need to disconnect in Thorswap
and then reconnect. My balances then display correctly.

Cheers,
Arron

**Comment by bullishtrader** [comment]
Yes, this is right.
Whenever you want to connect to a different wallet, you should refresh your browser or disconnect manually.

Glad it worked out, have a great day ahead =) @azza2902
