### ISSUE TITLE
STUCK/MISSING FUNDS

### ISSUE THREAD

**Issue by mastosis** [thorswap/thorswap-finance-app#69]
I tried adding 1.98 of BNB to the BNB.RUNE pool.. going 50/50 with Rune. The transaction didn't go through however half of my BNB per the dex explorer has been sent to an unknown address.. and the other half is still in my wallet. Are my funds missing? i also cannot tell if the Rune side of the transaction went through.
It is worth to note that i tried withdrawing the other half in my wallet but that didn't go through as well
Tx hash--D5F057D28863849DB6EA3ECA74E3D144931D740B3B6E4EA243A616223155AEF6

address my bnb was sent to--bnb1ksxqxurvejkndenuv0alqawpr3e4vtqk855aal
[Screenshot 2021-04-15 at 7.59.02 AM 2.pdf](https://github.com/thorswap/thorswap-finance-app/files/6316255/Screenshot.2021-04-15.at.7.59.02.AM.2.pdf)

**Comment by mastosis** [comment]
ok i have been able to withdraw half of the funds.. Now any idea as to how i can retrieve what was sent to bnb1ksxqxurvejkndenuv0alqawpr3e4vtqk855aal

**Comment by eode** [comment]
It's likely a known bug that is affecting all of the wallets.  Part of it is due to a miscalculation of the RUNE transaction fees.
Basically, the RUNE transaction doesn't go through, then the pool contribution isn't recognized.  If that's what happened to you, don't worry, your funds are safe, and they're working on a fix.
